SET SCHEMA MMIPROD;

SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OING"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLAB"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLOC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OQCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORSH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OWRD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCTG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCTL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCVC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCVI"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCVR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODDA"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODEF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODEG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODTRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ODTRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OECL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OEET"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OHCF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OICG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OICH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OICL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OICS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OICT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIDT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIDV"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIGC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIGG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIGT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIHG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLOQ"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMOR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ONTR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ONUT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OOCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OOHT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OOPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OOTR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPDC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APRT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APVR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AQCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARAC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARCL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARCM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARNN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARSG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARSN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_BSSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_CONFIG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARTG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARWRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASCRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASHF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASIT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATCG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATCL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATEM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATPG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATPT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ATRT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AVLPL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AWRD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AWRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIID"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OABT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OAJE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OALG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OATR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OBOM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OBTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCAL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCLS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCMP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OCPL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AOPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AOTR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APDC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APLR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APNO"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APOR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APRD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APRE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APRO"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_APRR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PC_ACCF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PC_ACCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORSN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORTG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORWRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORWRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSCRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSCRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSHF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSIT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTCG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTCL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTEM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTPG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTPT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTQY"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OTRT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OUST"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OVLPL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OWRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACMP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACPL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACTG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACTL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACVC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACVI"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ADDA"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ADEF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ADEG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ADTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ADTRS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AECL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AICG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AICH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AICS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AICT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIDT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AABT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AAJE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AALG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AATR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ABOM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ABTM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACAL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACLS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AHCF"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIGC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIGG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIGT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIHG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIID"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIMD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AING"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AINN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AINS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIOP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIPCL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIPG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIPH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ACVR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AEET"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIOCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OQCP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AQCP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OWLG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OWDC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AWDC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMRL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMRL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMRC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMRC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMFC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMFC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OSCE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ASCE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AITC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AITG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AITL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AITX"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIUL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AIVD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALAB"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALAT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALAV"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALMD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALOC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ALOQ"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMOR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ANTR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ANUT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AOCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AOIRG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIOCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ARSH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OMAR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_AMAR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIMD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OINN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OINS"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIOP"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIPG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIPH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIPR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OITC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OITG"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OITL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OITX"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OIUL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLAT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLAV"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OLMD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPDL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPLR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPNO"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPOR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPRD"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPRE"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPRO"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPRR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPRT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_OPVR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORAC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORCH"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORCL"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORCM"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORCT"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORGR"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORNN"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORSC"
UNION
SELECT DISTINCT "U_PFDBVersion", "U_PFVersion" from "@CT_PF_ORSG";
